export const technologies = [
  {
    name: "TypeScript",
    icon: "https://cdn.simpleicons.org/typescript/c80036",
    alt: "TypeScript",
    category: "Language",
  },
  {
    name: "Go",
    icon: "https://cdn.simpleicons.org/go/c80036",
    alt: "Go",
    category: "Language",
  },
  {
    name: "POSTGRESQL",
    icon: "https://cdn.simpleicons.org/postgresql/c80036",
    alt: "POSTGRESQL",
    category: "Language",
  },
  {
    name: "Docker",
    icon: "https://cdn.simpleicons.org/docker/c80036",
    alt: "Docker",
    category: "Tool",
  },
  {
    name: "HTML",
    icon: "https://cdn.simpleicons.org/html5/c80036",
    alt: "HTML",
    category: "Web",
  },
  {
    name: "CSS",
    icon: "https://img.icons8.com/ios-filled/50/c80036/css3.png",
    alt: "CSS3",
    category: "Web",
  },
  {
    name: "React",
    icon: "https://cdn.simpleicons.org/react/c80036",
    alt: "React",
    category: "Web",
  },
  {
    name: "Svelte",
    icon: "https://cdn.simpleicons.org/svelte/c80036",
    alt: "Svelte",
    category: "Web",
  },
  {
    name: "C#",
    icon: "https://img.icons8.com/?size=100&id=111972&format=png&color=c80036",
    alt: "C#",
    category: "Language",
  },
  {
    name: "Unity",
    icon: "https://cdn.simpleicons.org/unity/c80036",
    alt: "Unity",
    category: "Game Engine",
  },
  {
    name: "C++",
    icon: "https://cdn.simpleicons.org/cplusplus/c80036",
    alt: "C++",
    category: "Language",
  },
  {
    name: "Tailwind CSS",
    icon: "https://cdn.simpleicons.org/tailwindcss/c80036",
    alt: "TailwindCSS",
    category: "Web",
  },
  {
    name: "Arch",
    icon: "https://cdn.simpleicons.org/archlinux/c80036",
    alt: "Arch",
    category: "OS",
  },
  {
    name: "Fedora",
    icon: "https://cdn.simpleicons.org/fedora/c80036",
    alt: "Fedora",
    category: "OS",
  },
  {
    name: "Ubuntu",
    icon: "https://cdn.simpleicons.org/ubuntu/c80036",
    alt: "Ubuntu",
    category: "OS",
  },
  {
    name: "Debian",
    icon: "https://cdn.simpleicons.org/debian/c80036",
    alt: "Debian",
    category: "OS",
  },
  {
    name: "Git",
    icon: "https://cdn.simpleicons.org/git/c80036",
    alt: "Git",
    category: "Tool",
  },
  {
    name: "GitHub",
    icon: "https://cdn.simpleicons.org/github/c80036",
    alt: "GitHub",
    category: "Tool",
  },
];
